project:
  type: website
  render:
    - "*.qmd"
    # - "*.Rmd"
    # - "*.md"
    # - "!README.md"
    # - "!LICENSE.md"
    # - "!myresources/"
    # - "!certificate*"
  resources:
    - "files/"
  preview:
    port: 4321
    browser: true

execute:
  # Re-render only when source changes
  freeze: auto

description-meta: "R. Heller's personal website."

# Enable banner style title blocks
title-block-banner: true

website:
  title: "R. Heller" 
  site-url: https://www.r-heller.com
  repo-url: https://github.com/r-heller/r-heller.github.io
  description: "Website of R. Heller"
  favicon: /files/icon.png
  navbar:
    background: "#2D3E50"
    logo: /files/logo.png
    left: 
      - text: About
        href: about.qmd 
      - text: Posts
        menu:
          - text: Biomedicine
            href: posts.qmd 
          - text: Data analysis
            href: analysis.qmd
      - text: Methods
        menu:
          - text: Dependenzanalyse [DE]
            href: dependencyanalysis.qmd
    right:
      - text: Ressources
        menu:
          - text: R Weekly
            href: https://rweekly.org/
          - text: R Bloggers
            href: https://www.r-bloggers.com/
      - text: Projects 
        href: projects.qmd 
      - text: Publications
        href: publications.qmd
      - text: Archive
        href: archive.qmd 
      - text: Legal [DE/EN]
        menu:
          - text: Impressum [DE]
            href: impressum_de.qmd
          # - text: Cookies [DE]
          #   href: cookies_policy_de.qmd
          # - text: Datenschutzerklärung [DE]
          #   href: privacy_policy_de.qmd
          - text: Legal notice [EN]
            href: impressum_en.qmd
          # - text: Cookies policy [EN]
          #   href: cookies_policy_en.qmd
          # - text: Privacy policy [EN]
          #   href: privacy_policy_en.qmd
      - icon: github
        href: https://github.com/r-heller
  cookie-consent:
    type: implied
    style: headline
    palette: light
    policy-url: "https://r-heller.com/cookies_policy_en.html"
    prefs-text: "Review cookie preferences"
  google-analytics:
    tracking-id: "G-7T94VJMY2C"
    storage: cookies # none
  search: true
  page-footer:
    left: |
      {{< fa regular copyright >}} R. Heller, 2023<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [A. Handel](https://www.andreashandel.com/) and [A. Rapp](https://albert-rapp.de/)<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/r-heller/r-heller.github.io)

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: customstyle.css 
    toc: true
    include-in-header: gtm_code_head.html
    include-before-body: gtm_code_body.html
    include-after-body: cookie_consent.html
