project:
  type: website

website:
  title: "R. Heller" 
  site-url: https://www.r-heller.com
  repo-url: https://github.com/r-heller/r-heller.github.io
  description: "Website of R. Heller"
  favicon: /files/icon.png
  google-analytics: "G-7T94VJMY2C"
  navbar:
    background: "#2D3E50"
    logo: /files/logo.png
    left: 
      - text: About
        href: about.qmd 
      - text: Posts
        menu:
          - text: Biomedicine
            href: posts.qmd 
          - text: Data analysis
            href: analysis.qmd
      - text: Methods
        menu:
          - text: Entscheidungsbaum
            href: methods.qmd
        
    right:
      - text: Ressources
        menu:
          - text: R Weekly
            href: https://rweekly.org/
          - text: R Bloggers
            href: https://www.r-bloggers.com/
      - text: Projects 
        href: projects.qmd 
      - text: Publications
        href: publications.qmd
      - text: Archive
        href: archive.qmd 
      - text: Impressum
        menu:
          - text: DE
            href: impressum.qmd
          - text: EN
            href: impressum.qmd
      - icon: github
        href: https://github.com/r-heller

  cookie-consent: true



# filters:
#   - code-filename

  page-footer:
    left: |
      {{< fa regular copyright >}} R. Heller, 2023<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [A. Handel](https://www.andreashandel.com/) and [A. Rapp](https://albert-rapp.de/)<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/r-heller/r-heller.github.io)
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly