project:
  type: website

website:
  title: "R. Heller" 
  site-url: https://r-heller.com
  description: "This is R. Heller's personal website."
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/AlbertRapp
      - icon: twitter
        href: https://twitter.com/rappa753
      - icon: youtube
        href: https://www.youtube.com/user/Alfrodo123
#########################
# You can ignore this part in the first step
#       - icon: rss
#         href: blog.xml
#       - text: Ressources
#         menu: 
#           - text: DataViz Portfolio
#             href: dataviz_portfolio.html
#           - text: YARDS
#             href: https://yards.albert-rapp.de/
#           - text: R Weekly
#             href: https://rweekly.org/
#           - text: R Bloggers
#             href: https://www.r-bloggers.com/
#       - text: Archive
#         href: archive.qmd
#   google-analytics: <Insert your ID here>
#   cookie-consent: true
#   twitter-card: 
#     image: thumbnail_blog.png
#     card-style: summary_large_image
#     creator: "@rappa753"
# 
# filters:
#   - code-filename
######################### 

format:
  html:
    theme: theme.scss